# Storage Configuration
STORAGE:
  TYPE: FLATFILE # Options: MONGODB, FLATFILE

MONGO:
  URI:
    ENABLED: false
    CONNECTION: 'mongodb://localhost:27017'
    DATABASE: 'souppvp'
  HOST: 'localhost'
  PORT: 27017
  DATABASE: 'souppvp'
  AUTHENTICATION:
    ENABLED: false
    USERNAME: 'admin'
    PASSWORD: 'password'
    AUTHENTICATION-DATABASE: 'admin'

SPAWN:
  LOCATION-A: world:30:91:30
  LOCATION-B: world:-30:201:-30

EVENTS:
  SUMO:
    SPECTATOR-SPAWN: world:-10000:89:-10025:0:0.5
    SPAWN-A: world:-10000:89:-10025:0:0.5
    SPAWN-B: world:-10000:89:-10025:0:0.5

FREE-KITS: false