name: Default
rarity: COMMON
price: 0
icon:
  ==: org.bukkit.inventory.ItemStack
  type: DIAMOND_SWORD
description:
- '&7The basic PvP kit that all players have access to. There are no'
- '&7special abilities but this kit is still durable against others.'
enabled: true
combatEquipments:
- ==: org.bukkit.inventory.ItemStack
  type: DIAMOND_SWORD
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    enchants:
      DAMAGE_ALL: 1
armor:
- ==: org.bukkit.inventory.ItemStack
  type: IRON_BOOTS
- ==: org.bukkit.inventory.ItemStack
  type: IRON_LEGGINGS
- ==: org.bukkit.inventory.ItemStack
  type: IRON_CHESTPLATE
- ==: org.bukkit.inventory.ItemStack
  type: IRON_HELMET
potionEffects:
- ==: PotionEffect
  effect: 1
  duration: 2147483647
  amplifier: 0
  ambient: true
  has-particles: true
primaryAbility: None
secondaryAbility: None
